### ISSUE TITLE
Personal ID number is not showcased in profile of job applicant - should be

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#436]
![skarmavbild 2016-05-19 kl 15 12 54](https://cloud.githubusercontent.com/assets/16607246/15394610/3fe69ab0-1dd4-11e6-93e4-7b46eaf17681.png)

**Comment by chris-sedp** [comment]
Personal ID is not sent back from the API. @buren shall we show this or remove the row ?

**Comment by FivelFred** [comment]
@buren they need to be able to edit their person ID number (if they change from samordningsnummer to personal ID number). Do you see any issues with this.?

**Comment by buren** [comment]
Its always been possible to update a users ssn from the API, [see the docs](https://api.justarrived.se/api_docs/1.0/users/update.html) (!).

The API doesn't return the users ssn, but will, shortly (if the current user is allowed to view). Fixed in https://github.com/justarrived/just_match_api/commit/7e35aa16cf3b2b85b08cd80f4f9b1966fa9ee23a

**Comment by FivelFred** [comment]
Looks like this has been fixed.
