### ISSUE TITLE
Replace "Username" with "Email" in login form

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-frontend#492]
Currently the login form says "Användarnamn"/"Username" instead of email, which is what the API expects the user to fill in.

<img width="556" alt="screen shot 2016-05-23 at 09 13 43" src="https://cloud.githubusercontent.com/assets/922411/15463016/d34b441e-20c6-11e6-8c3c-d5fbf6256777.png">

**Comment by lenaar** [comment]
there is no actually any translation for **login.form.email** (field label) and **login.form.email.validation** (error message), there is only for username.
The solution: I can reuse **user.form.email** it has right translation, but then for error message will be 'you need to enter a valid email' instead of 'Epost missing', if it is ok?
