### ISSUE TITLE
Add a few input fields in the registration process of job performer

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#568]
We need to complement the existing input fields to ensure a few things:

Current status: Asylumseeker O     Permanent Residence O
AT-UND: Yes O   No O
Time in Sweden: Years O Months O
Country of origin:

**Comment by buren** [comment]
Seems like good information to include.. 

I'd propose that instead of "Time in Sweden" (which would change over time), we'd add "Arrived to Sweden" instead that way we can "calculate" the time they've been in Sweden.

**Comment by FivelFred** [comment]
This needs to be higher prioritized and fixed prior to full launch

**Comment by buren** [comment]
@FivelFred I agree. Created an issue for the API ☝️. 

We should also make sure we have some sort of plan of how to get users to update `Current status` if it's changed, otherwise we risk having bad data laying around. I have no idea what the best approach would be, but maybe something along the lines of a reminder every X months to update or confirm their `Current status`.

**Comment by buren** [comment]
These fields have been added in the API https://api.justarrived.se/api_docs/1.0/users/create.html.

So this is good to go :)
