### ISSUE TITLE
Bank-BIC alternative should be a link in the description and not a big pink button

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#623]
To start with, thanks @ti-sedp for implementing this feature. One small alternation I would like to do is to remove the pink button and put the feature into the description as a hypertext. 

This is how it looks now:

![current bank account details](https://cloud.githubusercontent.com/assets/16607246/16197226/892f87cc-3701-11e6-833e-303f455ebfd1.png)

This is how I want it to look: 

![future bank account details](https://cloud.githubusercontent.com/assets/16607246/16197220/7fda53f0-3701-11e6-8b00-000ac97b2da4.PNG)

**Comment by FivelFred** [comment]
@lenaar or @pstenstrm could you assist with this one or should I ask SEDP?

**Comment by lenaar** [comment]
@FivelFred: hi, yes I can, these two days I am at the google summit, will fix it after it. :)

**Comment by FivelFred** [comment]
OK thanks @lenaar !

**Comment by FivelFred** [comment]
Have you had time to look into this @lenaar ?

**Comment by lenaar** [comment]
I have fixed link instead of button, I have to do the whole sentence as the link because it is translatable text, cannot break it for putting link in the middle of it. The whole sentence looks better, because we understand that is link specific for this line.
<img width="1023" alt="screen shot 2016-07-14 at 15 21 45" src="https://cloud.githubusercontent.com/assets/2598785/16841023/b5c1b100-49d7-11e6-8e60-5a0ac435f37d.png">
<img width="602" alt="screen shot 2016-07-14 at 15 21 59" src="https://cloud.githubusercontent.com/assets/2598785/16841033/bf4a4160-49d7-11e6-88f5-46af149ccfe9.png">

**Comment by lenaar** [comment]
Probably we need more descriptive text for cancel, smth like 'Back to Use Bank Swedish Bank'

**Comment by buren** [comment]
Thanks @lenaar! :tada:

:+1: for a more descriptive "Cancel button".

**Comment by buren** [comment]
This has been implemented. Thanks again @lenaar
