### ISSUE TITLE
Error on phone number when updating password (front- or back-end?)

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#629]
When I try to update my profile as job applicant and I change my password and then click save the system indicates that my phone number is wrong (see below). Is this a beacuse my phone number is registered 20 times in various accounts and is now set as an identification parameter by back-end or is it a front-end bug? 

![skarmavbild 2016-06-20 kl 18 26 45](https://cloud.githubusercontent.com/assets/16607246/16202245/256cea2c-3715-11e6-95b0-1c16ae4fa5e2.png)

**Comment by pstenstrm** [comment]
Can we avoid re-validating fields if they contain the same information as we got from the API, or would this mean a security issue?

So whatever we receive from the backend we simply don't validate in the frontend.

**Comment by FivelFred** [comment]
sounds good to me. is this error "provoked" back-end or front-end? @buren

**Comment by buren** [comment]
Hm @psenstrm, I'm kinda uncomfortable doing that, the main reason is just what you state security. 

@FivelFred the reason you require seeing that error is that since we added "login with phone number" the phone number has to be unique. Previously the API didn't validate that, which was a bug, and each time you update any resources all of its validations are run. In other words things like this shouldn't happen ;) 

The frontend seems to understand that there is an error on the phone field but doesn't show the description, which the API returns. I think it should :) 

Lastly let us (@FivelFred) discus on the phone what we should do with the bad data that is currently in the system.

**Comment by ti-sedp** [comment]
Fixed, show error detail in form
![2559-06-21_16h36_26](https://cloud.githubusercontent.com/assets/16758634/16232824/37609404-37f6-11e6-9089-75e516f49415.png)
