### ISSUE TITLE
Allow assigned and performed jobs to be visible (but not possible to apply for)

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#667]
Currently jobs are removed from the Find jobs and New jobs list when a job performer has confirmed that he/she will perform it. That makes sense from a product perspective but as companies enter the site it would be beneficial if they saw a lot of jobs as examples but also to make them feel comfortable with adding a job that a lot of other companies has used. 

My suggestion is that front-end retrieves jobs with parameter `filled` set to false from the api. If that is true, the front-end should show the job but remove the apply button. Instead it should show a text like;

'Not available' (larger text)
'Job performer has already been confirmed' (smaller text)

**Comment by FivelFred** [comment]
@ti-sedp; If you need input on how to do this technically, please advice @buren

**Comment by buren** [comment]
Relevant places in the code: https://github.com/justarrived/just-match-frontend/search?utf8=%E2%9C%93&q=filled

@FivelFred do you think that the jobs in the listing should have some indicator that they've already been filled? (I think the risk otherwise might be that users click in on each and every job, just to be informed that it has already been filled.)

**Comment by chris-sedp** [comment]
I take this one!
